on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: windows-latest
    steps:
      - name: Run tests
        run: npx vitest run --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: naumalex/react